#ifndef OUTPUT_TEST__TESTMODE_H_
#define OUTPUT_TEST__TESTMODE_H_

enum TestMode {
  PRINTF = 1,
  COUT_SYNC_WITH_STDIO_TRUE,
  COUT_SYNC_WITH_STDIO_FALSE,
  COUT_SYNC_WITH_STDIO_FALSE_TIE_NULLPTR
};

#endif //OUTPUT_TEST__TESTMODE_H_
